# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 551c767f5ad4c81ebe8ed2a640054399d5bfc658f1da23dc8a618a4d0b592837d052d20ad73d2cf534a75eb464aa4d8da8e0464aa53f66a684f37cffa9c53fd3

test:
  secret_key_base: ee654bfbd8f90f6005f365e22582fc21fdf1bf0feaa15806f93107897a86eb602a8302e58a43e5cc7b629e16e69de9effeb4f769bcafb9420b9586ff95c28a3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
